import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";
import { users } from "./users";

/**
 * FIDO2 / WebAuthn passkey credentials registered to user accounts.
 */
export const passkeys = sqliteTable("passkeys", {
	/**
	 * Unique identifier for the passkey record.
	 */
	id: text("id").primaryKey(),

	/**
	 * User account owning this passkey.
	 */
	userId: text("user_id")
		.notNull()
		.references(() => users.id, {
			onDelete: "cascade",
		}),

	/**
	 * Base64URL-encoded WebAuthn credential identifier generated by authenticator.
	 */
	credentialId: text("credential_id").notNull().unique(),

	/**
	 * Public key bytes encoded in COSE/CBOR format used to verify cryptographic authentication assertions.
	 */
	publicKey: text("public_key").notNull(),

	/**
	 * Monotonically increasing signature counter used for authenticator clone detection.
	 */
	counter: integer("counter").notNull().default(0),

	/**
	 * JSON-encoded array of supported transports (e.g. 'internal', 'hybrid', 'usb', 'ble', 'nfc').
	 */
	transports: text("transports"),

	/**
	 * User-friendly label for the credential (e.g. 'MacBook Touch ID', 'YubiKey 5C NFC').
	 */
	name: text("name"),

	/**
	 * Authenticator Attestation GUID identifying the make/model of the authenticator.
	 */
	aaguid: text("aaguid"),

	/**
	 * Boolean flag indicating if the passkey is backed up to a multi-device synced keychain (true) or single-device hardware key (false).
	 */
	backedUp: integer("backed_up", { mode: "boolean" }),

	/**
	 * Credential device type classification ('singleDevice' | 'multiDevice').
	 */
	deviceType: text("device_type"),

	/**
	 * Epoch timestamp (ms) when this passkey was registered.
	 */
	createdAt: integer("created_at").notNull(),

	/**
	 * Epoch timestamp (ms) when this passkey was last used to authenticate.
	 */
	lastUsedAt: integer("last_used_at"),
});

export type Passkey = typeof passkeys.$inferSelect;
export type NewPasskey = typeof passkeys.$inferInsert;
