import { existsSync, readFileSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const ROOT_DIR = resolve(import.meta.dir, "..");
const ENV_FILE = resolve(ROOT_DIR, ".env");
const TFVARS_FILE = resolve(ROOT_DIR, "terraform/terraform.tfvars");

/**
 * Parses key-value pairs from a .env file.
 */
function parseEnvFile(filePath: string): Record<string, string> {
	if (!existsSync(filePath)) {
		return {};
	}

	const content = readFileSync(filePath, "utf8");
	const env: Record<string, string> = {};

	for (const rawLine of content.split("\n")) {
		const line = rawLine.trim();
		if (!line || line.startsWith("#")) continue;

		const eqIdx = line.indexOf("=");
		if (eqIdx === -1) continue;

		const key = line.slice(0, eqIdx).trim();
		let val = line.slice(eqIdx + 1).trim();

		// Remove matching surrounding quotes
		if (
			(val.startsWith('"') && val.endsWith('"')) ||
			(val.startsWith("'") && val.endsWith("'"))
		) {
			val = val.slice(1, -1);
		}

		env[key] = val;
	}

	return env;
}

const fileEnv = parseEnvFile(ENV_FILE);

function getEnv(key: string): string | undefined {
	return process.env[key] || fileEnv[key];
}

function cleanDomain(domain?: string): string {
	if (!domain) return "";
	return domain.replace(/^https?:\/\//, "").replace(/\/+$/, "");
}

const cloudflareAccountId = getEnv("CLOUDFLARE_ACCOUNT_ID")?.trim();
const cloudflareZoneId = getEnv("CLOUDFLARE_ZONE_ID")?.trim();
const instanceName = getEnv("INSTANCE_NAME")?.trim() || "muljax-id";

const dashboardDomain = cleanDomain(getEnv("DASHBOARD_DOMAIN"));
const apiDomain = cleanDomain(getEnv("API_DOMAIN"));

const localhost = getEnv("LOCALHOST")?.toLowerCase() === "true";
const adminBootstrapSecret = getEnv("ADMIN_BOOTSTRAP_SECRET")?.trim();
const oidcPrivateKeyEnv = getEnv("OIDC_PRIVATE_KEY")?.trim();

const missing: string[] = [];
if (!cloudflareAccountId) missing.push("CLOUDFLARE_ACCOUNT_ID");
if (!cloudflareZoneId) missing.push("CLOUDFLARE_ZONE_ID");
if (!dashboardDomain) missing.push("DASHBOARD_DOMAIN");
if (!apiDomain) missing.push("API_DOMAIN");
if (!adminBootstrapSecret) missing.push("ADMIN_BOOTSTRAP_SECRET");

if (missing.length > 0) {
	console.error("❌ Error: Missing required environment variable(s) in .env:");
	for (const varName of missing) {
		console.error(`   - ${varName}`);
	}
	process.exit(1);
}

// Preserve existing oidc_private_key if already generated
let oidcPrivateKey = oidcPrivateKeyEnv || "replace-me";

if (!oidcPrivateKeyEnv && existsSync(TFVARS_FILE)) {
	try {
		const existingTfvars = readFileSync(TFVARS_FILE, "utf8");
		const match = existingTfvars.match(/^oidc_private_key\s*=\s*(.*)$/m);
		if (match?.[1]) {
			const val = match[1].trim();
			if (
				val &&
				val !== '""' &&
				val !== '"replace-me"' &&
				val !== "replace-me"
			) {
				try {
					oidcPrivateKey = JSON.parse(val);
				} catch {
					oidcPrivateKey = val;
				}
			}
		}
	} catch {
		// Ignore read error
	}
}

const tfvarsContent = `# Auto-generated from .env by "bun run vars"
# Do not commit this file to version control.

cloudflare_account_id = ${JSON.stringify(cloudflareAccountId)}
cloudflare_zone_id    = ${JSON.stringify(cloudflareZoneId)}

instance_name = ${JSON.stringify(instanceName)}

api_domain       = ${JSON.stringify(apiDomain)}
dashboard_domain = ${JSON.stringify(dashboardDomain)}

localhost = ${localhost}

admin_bootstrap_secret = ${JSON.stringify(adminBootstrapSecret)}

oidc_private_key = ${JSON.stringify(oidcPrivateKey)}
`;

await writeFile(TFVARS_FILE, tfvarsContent);
console.log(`✅ Successfully generated ${TFVARS_FILE} from .env`);

const protocol = localhost ? "http" : "https";
const derivedApiUrl = `${protocol}://${apiDomain}`;

const autogenHeader =
	"# ------------------------------------------------------------\n# AUTOGENERATED (Derived by `bun run vars`)";
const autogenContent = `${autogenHeader}\nVITE_API_URL=${derivedApiUrl}\nOIDC_ISSUER=${derivedApiUrl}\n`;

if (existsSync(ENV_FILE)) {
	let currentEnv = readFileSync(ENV_FILE, "utf8");

	// If there's an existing autogenerated block, replace it
	const autogenIdx = currentEnv.indexOf(autogenHeader);
	if (autogenIdx !== -1) {
		currentEnv = currentEnv.slice(0, autogenIdx).trimEnd();
	} else {
		// Also strip any standalone manually defined VITE_API_URL / OIDC_ISSUER lines if present
		currentEnv = currentEnv
			.split("\n")
			.filter(
				(l) =>
					!l.trim().startsWith("VITE_API_URL=") &&
					!l.trim().startsWith("OIDC_ISSUER="),
			)
			.join("\n")
			.trimEnd();
	}

	const updatedEnv = `${currentEnv}\n\n${autogenContent}`;
	await writeFile(ENV_FILE, updatedEnv);
	console.log(`✅ Updated derived variables in ${ENV_FILE}`);
}
